### PR TITLE
use flit instead of poetry

### PR DESCRIPTION
**Pull request by orsinium**
Merge it when #91 will be released on pypi

### CODE REVIEW

**Comment by dbanty** [comment]
Just curious what the benefits are to flit, why use it instead of Poetry?

**Comment by orsinium** [comment]
1. Dephell can process yaml with pyyaml or ruamel.yaml. Ruamel.yaml is preferred, because preserve comments, but cannot be installed on pypy because of bug in pip. So, I need to depends on ruamel.yaml on all implementations except pypy. However, poetry doesn't support custom markers or markers for implementation, only platform name and python version.
1. Poetry doesn't support custom links. Only home, repository and documentation. That's not enough. For example, Django has link on donation page. And I want to insert link on [DepHell's Twitter](https://twitter.com/PythonDepHell)

**Comment by jayvdb** [comment]
not related to flit vs poetry, but ..

@orsinium , there have been some significant changes in ruamel.yaml , especially wrt packaging due to https://bitbucket.org/ruamel/yaml.convert/issues/1/ and https://bitbucket.org/ruamel/yaml.convert/issues/2/ ,

The main package definitely works on PyPy , and the 'clib' subpackage with the optimised C library is now quite separate and optional, so it shouldnt cause a problem for PyPY, but I am doing a build of pypy now to check it.

**Comment by orsinium** [comment]
Thank you, I'll try
#275

**Comment by orsinium** [comment]
Ok, let's back to it later. I already have a few projects on flit, and it's quite good experience.

**Pull request closed without merging**
