### PR TITLE
Improve installer for Windows platform

### LINKED ISSUE #354: Installer fails on Windows
## Short description

Windows installation fails when used with official python for windows distribution.

## Output

Expected outcome - dephell installed.

## Steps to reproduce

1. Install Python from https://www.python.org/downloads/release/python-376/
2. Verify that python is installed correctly:
    ```dos
    >python --version
    Python 3.7.6
    ```
3. `curl -L dephell.org/install | python`

## Details

First, the installer [searches](https://github.com/dephell/dephell/blob/a05bfad7c51d428f53ea0c114de88aab93808b61/install.py#L66) for python3. There is no `python3` binary on Windows.

Then, if I change it so that python is found, there is another error:
```rem
copy binary dephell
DepHell binary not found
```
Looking at files in virtual environment folder, it seems that dephell was indeed installed, but [local_path](https://github.com/dephell/dephell/blob/a05bfad7c51d428f53ea0c114de88aab93808b61/install.py#L104) fails as binary on Windows is `dephell.exe` and not `dephell`.

### PR DESCRIPTION
**Pull request by fralik**
- Small improvements to the installer so it runs fine on Windows (correct binary names).
- Wrap installer code in a function. This is a tiny thing, but will make the script running a bit faster because Python won't search for variables in the global scope.

Fixes #354

### CODE REVIEW

**Comment by orsinium** [comment]
Great! Could you make these 2 fixes separate PRs or at least separate commits? For now, it's hard to say what was changed in the code because of moving things around. See [This Is Why You Always Review Your Dependencies](https://www.agwa.name/blog/post/always_review_your_dependencies) for an example why this is important :)

**Comment by orsinium** [comment]
To be honest, the second thing even isn't important. The slowest part of the script is network requests, not variable lookups. But up to you, I'm ready to merge it if it will be in a separate PR with clear diff.

**Comment by fralik** [comment]
OK. It is A PR with one commit now, which fixes the installer.  Code wrapping is left behind.

**Comment by orsinium** [comment]
Great! Thank you. I'll take care of CI :)

**Pull request merged**
