### PR TITLE
.travis.yml: Try adding Windows to the mix

### PR DESCRIPTION
**Pull request by cclauss**
In [Travis CI Windows](https://docs.travis-ci.com/user/reference/windows):
```
where py || true       # C:\Windows\py.exe
which py || true       # /c/Windows/py
where python || true   # C:\Python37\python.exe and C:\ProgramData\chocolatey\bin\python.exe
which python || true   # /c/Python37/python
where python3 || true  # None!!!
which python3 || true  # None!!!
where pip || true      # C:\Python37\Scripts\pip.exe
which pip || true      # /c/Python37/Scripts/pip
where pip3 || true     # C:\Python37\Scripts\pip3.exe
which pip3 || true     # /c/Python37/Scripts/pip3
```

### CODE REVIEW

**Comment by orsinium** [comment]
Is it WIP PR, right?

**Comment by cclauss** [comment]
Yes...  WIP but I am kinda out of ideas if you have any advise.

**Comment by orsinium** [comment]
We've just closed #35 a few days ago, so Windows support on the way. I will have a look on it. I think, it will be better just to use appvyenvor (ugh, I always forget how to type it) for Windows CI. All packages in dephell ecosystem (like `dephell_venvs`) already tested on it, and it works :) However, I will be happy to have it on travis, so I will dive into messages in your PR, thank you.

**Comment by cclauss** [comment]
Closing to get outa Winhell.

**Comment by orsinium** [comment]
Dev version of dephell tested on ci by previous stable version of dephell from pypi. There is the problem: previous dephell version must work. However, this is not true for windows yet. Solution is not to use install.py at all and just install dephell from pypi by pip. Yeah, it will pollute site-packages, but we can return to install.py when all tests work.

**Pull request closed without merging**
