### PR TITLE
Removed useless prefixes of the links in the project

### PR DESCRIPTION
**Pull request by Kastakin**
As requested in the following issue #182

### CODE REVIEW

**Comment by orsinium** [comment]
Wow, that was fast. Thank you :) 

You've dropped these prefixes from external links (pytest, setuptools). Could you put it back, please? And check CI results, they are red by some reason.

**Comment by Kastakin** [comment]
I'm gonna bring the ones you pointed out back! 
The CI results show that some links are "bare-urls", I don't really know why they doesn't pass the test since I didn't change the formatting of the links but just the URL itself

**Comment by Kastakin** [comment]
My MDLinter had different parameters so I had to do a double commit to have the pull request to be checked by CI.

I fixed some broken links I messed up here and there while removing the prefixes, it should be ok now I think! :) 
Just let me know if you see something out of place!

**Comment by orsinium** [comment]
Perfect! Thank you for your help and congratulations with your first pull request :)

If you will be willing to dive a little into [sphinx](https://github.com/sphinx-doc/sphinx), we have a simple task in #180. Any contributions are always welcome here. And feel free to ask any questions and open issues for bugs and ideas.

**Pull request merged**
