### PR TITLE
Fixes issue: Correct use pathlib everywhere in tests #35

### PR DESCRIPTION
**Pull request by avallbona**
Fixes issue: Correct use pathlib everywhere in tests #35

### CODE REVIEW

**Comment by orsinium** [comment]
Thank you!

You can write `shutil.copy(str(Path(...)))`, and it will work for Python 3.5 too. No try-except needed. Could you fix it, please?

**Comment by avallbona** [comment]
Hi there, done!

**Comment by orsinium** [comment]
Wonderful! Thank you ^^

**Comment by orsinium** [comment]
Hey, Github, close #35

**Pull request merged**
