### PR TITLE
.travis.yml: Upgrade to current Python on current macOS

### PR DESCRIPTION
**Pull request by cclauss**
Why does upgrading from Python 3.6 --> 3.7 and macOS 10.13 --> 10.14 fail?

See table at https://docs.travis-ci.com/user/reference/osx/#jdk-and-macos

### CODE REVIEW

**Comment by orsinium** [comment]
IDK, some pip bugs on travis. Travis has no official support for Python. How I test dephell on Travis for mac os is a kind of hacks. Maybe, it's better don't touch it yet :D

**Comment by cclauss** [comment]
Don't mess with what is working...

**Comment by gram-eiq** [comment]
This output is similar to output in PR for Windows CI. Maybe, we will return to it in future :)

**Comment by orsinium** [comment]
This output is similar to output in PR for Windows CI. Maybe, we will return to it in future :)

**Pull request closed without merging**
