### PR TITLE
Sort 'package_data' keys in setup.py (#265)

### PR DESCRIPTION
**Pull request by ko3luhbka**

### CODE REVIEW

**Comment by ko3luhbka** [comment]
Sorry, forgot to run flake8 and isort checks

**Comment by jayvdb** [comment]
Some of the CI errors are due to https://github.com/dephell/dephell/pull/298

**Comment by ko3luhbka** [comment]
> Some of the CI errors are due to #298

You mean this?
> ./dephell/models/requirement.py:66:22: C407 Unnecessary list comprehension - 'sum' can take a generator.

**Comment by orsinium** [comment]
I think it was fixed in #292. Thank you for your help :)

**Pull request closed without merging**
