### PR TITLE
add missing dependency for certifi

### PR DESCRIPTION
**Pull request by jhermann**
certifi is used in "networking", and if you install using plain pip,
it is missing

### CODE REVIEW

**Comment by jhermann** [comment]
BTW, there is another problem (uncovered by dep convert):

```
  File "/home/jhe/src/github/dephell/.venv/dephell/lib/python3.6/site-packages/m2r-0.2.1-py3.6.egg/m2r.py", line 59, in <module>
    class RestBlockGrammar(mistune.BlockGrammar):
AttributeError: module 'mistune' has no attribute 'BlockGrammar'
```

mistune must be managed to <2. Upstream (m2r) has an issue mentioning this, but I saw no activity regarding fixing this.

**Comment by jhermann** [comment]
Probably best to cherry-pick the 2nd commit and then let the convert run on current HEAD.

**Comment by orsinium** [comment]
> mistune must be managed to <2. Upstream (m2r) has an issue mentioning this, but I saw no activity regarding fixing this.

Thank you. Meh, we should get rid of this md to rst convertion. Let's assume that everyone has setuptools actual enough. I've seen #392. It shows interest from the community in removing this feature.

**Comment by jhermann** [comment]
Ditch mistune, add related pandoc call to docs (or even call out to pandoc, replacing the current code).

**Comment by orsinium** [comment]
I think we can just drop this conversion. Setuptools and pypi support markdown already long enough.

**Pull request merged**
