### PR TITLE
Support allow-prereleases

### PR DESCRIPTION
**Pull request by 515hikaru**
See #322 

Now, there are two changes in this PR:

* Accept both allows-prerelease key and allow-prerelease key
* Write allow-prerelease key even if the original file had allow**s**-prereleases key.

Let me know if I have anything else to do.

### CODE REVIEW

**Comment by 515hikaru** [comment]
Self comment: It is too early to dumps allow-prerelease key only.
Poetry's stable version is 0.12.17 now. But the deprecated warnings are shown from 1.0.0.

**Comment by orsinium** [comment]
1. Let's always dump with the the old name (`allows-prereleases`), no matter which format was used before. 
2. And read it in any format, of course, you've done it perfect. 
3. And a few releases later we will change dump to the new format. 

I don't think we should make things complicated for that transition stage.

Thank you :)

**Comment by 515hikaru** [comment]
@orsinium Thank you for your comment :)
I changed to always dump the old key. I'm ready for review.

**Comment by 515hikaru** [comment]
Poetry 1.0.0 was released: https://python-poetry.org/blog/announcing-poetry-1-0-0.html

But current poetry supports both allow and allows key. So I won't change this PR.

**Comment by orsinium** [comment]
Perfect! Thank you :)

**Pull request merged**
