### PR TITLE
added inspect project command

### LINKED ISSUE #90: `inspect project` command
Read `from` and show json of `attr.asdict(root)`

### PR DESCRIPTION
**Pull request by jaibhageria**
Close #90.

The `inspect project` command works locally and gives the following output : 
```
$ python3 -m dephell inspect project
{
  "description": "A sample Python project",
  "raw_name": "sampleproject",
  "version": "1.4.0"
}
```
The JSON, right now has only 3 keys. More can be added if required
I have written a simple test file for `inspect project` which I tested using 
`dephell inspect project --env pytest`. 
More complex tests can be added to the test file if required.

I will proceed with the docs, if this was what is required to achieve.
Please suggest any changes if need be.

### CODE REVIEW

**Comment by jaibhageria** [comment]
The test script written by me fails. Please let me know how to write the test (what is wrong with my current test file?) and how to run the test locally

**Comment by jaibhageria** [comment]
> The test script written by me fails. Please let me know how to write the test (what is wrong with my current test file?) and how to run the test locally

Figured out how to test locally using pytest. Need help in writing the test, any suggestion will be appreciated.

**Comment by jaibhageria** [comment]
@orsinium 
I see that all checks in Travis have passed except for the this small issue:
```
./dephell/models/requirement.py:66:22: C407 Unnecessary list comprehension - 'sum' can take a generator.
```
This issue is in a file which I haven't modified in my commit.

**Comment by orsinium** [comment]
Thank you! Could you add docs for it as well, please?

**Pull request merged**
