### PR TITLE
WIP Adding tests for commands

### PR DESCRIPTION
**Pull request by nandahkrishna**
PR for issue #34 to add tests for commands. Sorry for the delay! Still working on this. Do review and give me your suggestions. Thanks.

### CODE REVIEW

**Comment by orsinium** [comment]
Good start. Keep it up :)

**Comment by nandahkrishna** [comment]
I'm not sure what I should do here to fix the test. I run the command and expect AUTHORS to be generated, but this depends on the git log, so should I make some artificial commits or is there some problem here?

**Comment by orsinium** [comment]
`argv` is required here:

```
GenerateAuthorsCommand(argv=[], config=config)
```

**Comment by orsinium** [comment]
> but this depends on the git log, so should I make some artificial commits or is there some problem here?

Yeah, you're thinking in the right directions. We have some tests that depends on git log of dephell itself, and we have much of the problems with them. Right solution here is to get `temp_path` fixture and create in this temporary directory a new git repo, set up username and email in git config and init it with some history.

**Comment by nandahkrishna** [comment]
Ah, alright. Thanks for the inputs!

**Comment by nandahkrishna** [comment]
Hello, sorry for the long absence. Been very busy with work so couldn't get around to finishing this. Is it alright if I close this in favour of someone else who can implement it?

I hope to return and contribute as soon as possible. Thanks!

**Comment by orsinium** [comment]
I close it to keep our review pipeline clearer. Feel free to reopen anytime. And keep in mind that you can run CI on your fork as well from your TravisCI account. Thank you for your contributions :+1:

**Pull request closed without merging**
